version: '3.4'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - my-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - my-network
      
  printly:
    build:
      context: ../
      dockerfile: Printly/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - my-network

      
networks:
  my-network:
    external: true