version: '3.4'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    networks:
      - my-network

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    restart: always
    networks:
      - my-network
      
  printly:
    build:
      context: ../
      dockerfile: Printly/Dockerfile
    environment:
      -  ASPNETCORE_URLS=http://0.0.0.0:5000/
      -  ASPNETCORE_ENVIRONMENT=Development
      -  PRINTLY_ServiceId=2E910612-CB54-4436-BCD7-890698BC4B2E
      -  PRINTLY_MongoDbStorageConnectionString=mongodb://mongo:27017
      -  PRINTLY_MongoDbStorageDatabaseName=Printly
      -  PRINTLY_SerialPortPollPauseMilliseconds=1000
      -  PRINTLY_TerminalReadBufferSize=4096
      -  PRINTLY_DefaultTerminalBaudRate=9600
      -  PRINTLY_DefaultTerminalDataBits=8
      -  PRINTLY_DefaultTerminalStopBits=1
      -  PRINTLY_DefaultTerminalParity=None
      -  PRINTLY_DefaultTerminalHandshake=None
      -  PRINTLY_DefaultReadTimeoutMilliseconds=10000
      -  PRINTLY_DefaultWriteTimeoutMilliseconds=10000
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    restart: always
    networks:
      - my-network
    volumes:
      - /dev:/dev
    privileged: true

networks:
  my-network:
    external: true