version: '3.4'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - my-network

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - my-network
      
  printly:
    build:
      context: ../
      dockerfile: Printly/Dockerfile
    environment:
      -  ASPNETCORE_URLS=http://localhost:5000/
      -  PRINTLY_ServiceId=2E910612-CB54-4436-BCD7-890698BC4B2E
      -  PRINTLY_MongoDbStorageConnectionString=mongodb://mongo:27017
      -  PRINTLY_MongoDbStorageDatabaseName=Printly
    ports:
      - "5000:5000"
    networks:
      - my-network

      
networks:
  my-network:
    external: true